### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by scutfrank** [ECNU-Cross-Innovation-Lab/mini-AORCNN#2]
RuntimeError: Given groups=1, weight of size [8, 3, 7, 7], expected input[32, 2, 112, 112] to have 3 channels, but got 2 channels instead

**Comment by scutfrank** [comment]
In models/arfnet.py

class ARFNet(nn.Module):
    def __init__(self, net_type='mhsa'):
        super(ARFNet, self).__init__()
        **# [N,2,112,112]**
        self.conv1 = nn.Sequential(
            nn.Conv2d(**in_channels=3**, out_channels=8, kernel_size=7, stride=2, padding=3),
            nn.ReLU(),
            nn.BatchNorm2d(8),
            # nn.MaxPool2d(kernel_size = 3,stride = 2,padding = 1)
        )

When i put in_channels from 3 to 2 ,it can run !

**Comment by Avalonsola** [comment]
Hi,it seems like we have the same problem.But i check the code found that in CASMECombinedDataset,there are not have OpticalFlow data,so may u need get opticalflow data by some other codes.

**Comment by Avalonsola** [comment]
this program is about mer,so without feature like opticalflow,it may only a program as expression recognition.The best to run the code is find a way to get some features.

**Comment by Avalonsola** [comment]
hey,now i fix it.here is the process:
1.**train_arg.py**  
`rom_file = 1
data_filename = 'dataset_112_strain.pkl'
data_class = CASMECombinedDataset
data_args = {'path': 'C:/Users/AzeroB/mini-AORCNN-master/dataset/', 'img_sz': 112, **_'calculate_strain': True_**}`
2.**data.py**
`def __init__(self, path='.',
                 img_sz=112,
                 **_calculate_strain=True_**,
                 initialized_df=None):`
And i also change `self.df['OpticalFlow'] = None` to `self.df['OpticalFlow'] = OpticalFlow` ,but i think you can keep use `None`

**Comment by QwQ2000** [comment]
The optical flow feature is a 2-channel feature map. If you need a 3-channel input, you should calculate the optical strain features when creating the dataset. Just let **calculate_strain = True**.

**Comment by scutfrank** [comment]
> The optical flow feature is a 2-channel feature map. If you need a 3-channel input, you should calculate the optical strain features when creating the dataset. Just let **calculate_strain = True**.

Can you share the link of this paper ,thanks !

**Comment by QwQ2000** [comment]
The journal paper for this code repository is under review, and you can refer to our conference paper:

> Zhang J, Liu F, Zhou A. Off-TANet: a Lightweight Neural Micro-Expression Recognizer with Optical Flow Features and Integrated Attention Mechanism[C]. Pacific Rim International Conference on Artificial Intelligence. Springer, Cham, 2021: 266-279.

**Comment by scutfrank** [comment]
> The journal paper for this code repository is under review, and you can refer to our conference paper:
> 
> > Zhang J, Liu F, Zhou A. Off-TANet: a Lightweight Neural Micro-Expression Recognizer with Optical Flow Features and Integrated Attention Mechanism[C]. Pacific Rim International Conference on Artificial Intelligence. Springer, Cham, 2021: 266-279.

I compare the model parameters between this mini-AORCNN and Off-TANet，seems the former is a lighter one，is there any block removal in mini-AORCNN from Off-TANet ?

**Comment by QwQ2000** [comment]
The attention mechanism and the design of the residual blocks are different. The design of the residual block is more parameter-saving in mini-AORCNN, and mini-AORCNN uses a Bottleneck Transformer instead of triplet attention.

**Comment by scutfrank** [comment]
> of the residual blocks are different

Got it,thanks!
