### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'dataset28x28_allclass_strain.pkl'

### ISSUE THREAD

**Issue by kuaixingxing** [ECNU-Cross-Innovation-Lab/mini-AORCNN#3]
![image](https://user-images.githubusercontent.com/91038531/177481488-82ecf002-0660-46e5-9b31-43abc83c5af1.png)
Hello, thank you very much for publishing your code on GitHub. I have a problem of "filenotfounderror: [errno 2] no such file or directory:'dataset28x28_allclass_strain.pkl'" in the process of trying to reproduce. I want to ask you this How do I get the pkl file? Do I need to do anything? Looking forward to your reply!

**Comment by QwQ2000** [comment]
Your problem looks similar to Issue #1. Here is my reply to that Issue.

> Construct a **CASMECombinedDataset** and save it as a file, just as the code in **train.py**:
> 
> ```python
> # train.py
> dataset = None
> if from_file:
>     with open(data_filename,'rb') as f:
>         dataset = pkl.load(f) 
> else:    
>     dataset = data_class(**data_args)
>     with open(data_filename,'wb') as f:
>         pkl.dump(dataset,f)
> ```
> 
> Configs related to dataset construction can be found in **train_arg.py**.
> 
> ```python
> # train_arg.py
> from_file = 1
> data_filename = 'dataset_112*112_strain.pkl'
> data_class = CASMECombinedDataset
> data_args = {'path':'/home/liuf/zjh/dataset','img_sz' : 112,'calculate_strain' : False}
> ```
